import {
  Monitor, Radio, Package, Headphones, Sparkles,
  CalendarDays, Users, BarChart3, ShieldCheck, Home,
  Mail, MessageSquare, Scissors, Tag, QrCode, ImageDown, FileOutput, Calculator, StickyNote
} from "lucide-react";

/**
 * Central registry for app identity: icon, colors, accent.
 * Used by Topbar, Sidebar, KonitysSwitcher, and Hub.
 */
const APP_IDENTITY = {
  "Konitys Hub": {
    icon: Home,
    bg: "bg-blue-50",
    text: "text-blue-600",
    accent: "blue",
    activeBg: "bg-blue-500/[0.08]",
    activeText: "text-blue-600",
    dot: "bg-blue-500",
    border: "border-blue-200",
    topStripe: "bg-blue-500",
    sidebarHover: "hover:bg-blue-500/[0.10]",
    sidebarActive: "bg-blue-500/[0.18]",
    sidebarActiveDot: "bg-blue-400",
  },
  "Bornes Manager": {
    icon: Monitor,
    bg: "bg-indigo-50",
    text: "text-indigo-600",
    accent: "indigo",         // CSS accent for active states
    activeBg: "bg-indigo-500/[0.08]",
    activeText: "text-indigo-600",
    dot: "bg-indigo-500",
    border: "border-indigo-200",
    topStripe: "bg-indigo-500",
    sidebarHover: "hover:bg-indigo-500/[0.10]",
    sidebarActive: "bg-indigo-500/[0.18]",
    sidebarActiveDot: "bg-indigo-400",
  },
  "Antennes Selfizee": {
    icon: Radio,
    bg: "bg-orange-50",
    text: "text-orange-600",
    accent: "orange",
    activeBg: "bg-orange-500/[0.08]",
    activeText: "text-orange-600",
    dot: "bg-orange-500",
    border: "border-orange-200",
    topStripe: "bg-orange-500",
    sidebarHover: "hover:bg-orange-500/[0.10]",
    sidebarActive: "bg-orange-500/[0.18]",
    sidebarActiveDot: "bg-orange-400",
  },
  "Stock Manager": {
    icon: Package,
    bg: "bg-emerald-50",
    text: "text-emerald-600",
    accent: "emerald",
    activeBg: "bg-emerald-500/[0.08]",
    activeText: "text-emerald-600",
    dot: "bg-emerald-500",
    border: "border-emerald-200",
    topStripe: "bg-emerald-500",
    sidebarHover: "hover:bg-emerald-500/[0.10]",
    sidebarActive: "bg-emerald-500/[0.18]",
    sidebarActiveDot: "bg-emerald-400",
  },
  "Support": {
    icon: Headphones,
    bg: "bg-amber-50",
    text: "text-amber-600",
    accent: "amber",
    activeBg: "bg-amber-500/[0.08]",
    activeText: "text-amber-600",
    dot: "bg-amber-500",
    border: "border-amber-200",
    topStripe: "bg-amber-500",
    sidebarHover: "hover:bg-amber-500/[0.10]",
    sidebarActive: "bg-amber-500/[0.18]",
    sidebarActiveDot: "bg-amber-400",
  },
  "Catalog IA": {
    icon: Sparkles,
    bg: "bg-violet-50",
    text: "text-violet-600",
    accent: "violet",
    activeBg: "bg-violet-500/[0.08]",
    activeText: "text-violet-600",
    dot: "bg-violet-500",
    border: "border-violet-200",
    topStripe: "bg-violet-500",
    sidebarHover: "hover:bg-violet-500/[0.10]",
    sidebarActive: "bg-violet-500/[0.18]",
    sidebarActiveDot: "bg-violet-400",
  },
  "Events Manager": {
    icon: CalendarDays,
    bg: "bg-rose-50",
    text: "text-rose-500",
    accent: "rose",
    activeBg: "bg-rose-500/[0.08]",
    activeText: "text-rose-500",
    dot: "bg-rose-500",
    border: "border-rose-200",
    topStripe: "bg-rose-500",
    sidebarHover: "hover:bg-rose-500/[0.10]",
    sidebarActive: "bg-rose-500/[0.18]",
    sidebarActiveDot: "bg-rose-400",
  },
  "Statistiques": {
    icon: BarChart3,
    bg: "bg-teal-50",
    text: "text-teal-600",
    accent: "teal",
    activeBg: "bg-teal-500/[0.08]",
    activeText: "text-teal-600",
    dot: "bg-teal-500",
    border: "border-teal-200",
    topStripe: "bg-teal-500",
    sidebarHover: "hover:bg-teal-500/[0.10]",
    sidebarActive: "bg-teal-500/[0.18]",
    sidebarActiveDot: "bg-teal-400",
  },
  "Abonnements": {
    icon: Users,
    bg: "bg-sky-50",
    text: "text-sky-500",
    accent: "sky",
    activeBg: "bg-sky-500/[0.08]",
    activeText: "text-sky-500",
    dot: "bg-sky-500",
    border: "border-sky-200",
    topStripe: "bg-sky-500",
    sidebarHover: "hover:bg-sky-500/[0.10]",
    sidebarActive: "bg-sky-500/[0.18]",
    sidebarActiveDot: "bg-sky-400",
  },
  "Admin": {
    icon: ShieldCheck,
    bg: "bg-stone-100",
    text: "text-stone-500",
    accent: "stone",
    activeBg: "bg-stone-500/[0.08]",
    activeText: "text-stone-500",
    dot: "bg-stone-500",
    border: "border-stone-200",
    topStripe: "bg-stone-500",
    sidebarHover: "hover:bg-stone-500/[0.10]",
    sidebarActive: "bg-stone-500/[0.18]",
    sidebarActiveDot: "bg-stone-400",
  },
  /* ── Utilitaires ─────────────────────── */
  "Emailing": {
    icon: Mail,
    bg: "bg-cyan-50",
    text: "text-cyan-600",
    accent: "cyan",
    activeBg: "bg-cyan-500/[0.08]",
    activeText: "text-cyan-600",
    dot: "bg-cyan-500",
    border: "border-cyan-200",
    topStripe: "bg-cyan-500",
    sidebarHover: "hover:bg-cyan-500/[0.10]",
    sidebarActive: "bg-cyan-500/[0.18]",
    sidebarActiveDot: "bg-cyan-400",
  },
  "Envoi SMS": {
    icon: MessageSquare,
    bg: "bg-lime-50",
    text: "text-lime-600",
    accent: "lime",
    activeBg: "bg-lime-500/[0.08]",
    activeText: "text-lime-600",
    dot: "bg-lime-500",
    border: "border-lime-200",
    topStripe: "bg-lime-500",
    sidebarHover: "hover:bg-lime-500/[0.10]",
    sidebarActive: "bg-lime-500/[0.18]",
    sidebarActiveDot: "bg-lime-400",
  },
  "Détourage Image": {
    icon: Scissors,
    bg: "bg-fuchsia-50",
    text: "text-fuchsia-600",
    accent: "fuchsia",
    activeBg: "bg-fuchsia-500/[0.08]",
    activeText: "text-fuchsia-600",
    dot: "bg-fuchsia-500",
    border: "border-fuchsia-200",
    topStripe: "bg-fuchsia-500",
    sidebarHover: "hover:bg-fuchsia-500/[0.10]",
    sidebarActive: "bg-fuchsia-500/[0.18]",
    sidebarActiveDot: "bg-fuchsia-400",
  },
  "Étiquettes UPS": {
    icon: Tag,
    bg: "bg-yellow-50",
    text: "text-yellow-600",
    accent: "yellow",
    activeBg: "bg-yellow-500/[0.08]",
    activeText: "text-yellow-600",
    dot: "bg-yellow-500",
    border: "border-yellow-200",
    topStripe: "bg-yellow-500",
    sidebarHover: "hover:bg-yellow-500/[0.10]",
    sidebarActive: "bg-yellow-500/[0.18]",
    sidebarActiveDot: "bg-yellow-400",
  },
  "QR Codes": {
    icon: QrCode,
    bg: "bg-slate-100",
    text: "text-slate-600",
    accent: "slate",
    activeBg: "bg-slate-500/[0.08]",
    activeText: "text-slate-600",
    dot: "bg-slate-500",
    border: "border-slate-200",
    topStripe: "bg-slate-500",
    sidebarHover: "hover:bg-slate-500/[0.10]",
    sidebarActive: "bg-slate-500/[0.18]",
    sidebarActiveDot: "bg-slate-400",
  },
  "Compresseur": {
    icon: ImageDown,
    bg: "bg-pink-50",
    text: "text-pink-600",
    accent: "pink",
    activeBg: "bg-pink-500/[0.08]",
    activeText: "text-pink-600",
    dot: "bg-pink-500",
    border: "border-pink-200",
    topStripe: "bg-pink-500",
    sidebarHover: "hover:bg-pink-500/[0.10]",
    sidebarActive: "bg-pink-500/[0.18]",
    sidebarActiveDot: "bg-pink-400",
  },
  "Convertisseur PDF": {
    icon: FileOutput,
    bg: "bg-red-50",
    text: "text-red-600",
    accent: "red",
    activeBg: "bg-red-500/[0.08]",
    activeText: "text-red-600",
    dot: "bg-red-500",
    border: "border-red-200",
    topStripe: "bg-red-500",
    sidebarHover: "hover:bg-red-500/[0.10]",
    sidebarActive: "bg-red-500/[0.18]",
    sidebarActiveDot: "bg-red-400",
  },
  "Calculatrice Devis": {
    icon: Calculator,
    bg: "bg-teal-50",
    text: "text-teal-600",
    accent: "teal",
    activeBg: "bg-teal-500/[0.08]",
    activeText: "text-teal-600",
    dot: "bg-teal-500",
    border: "border-teal-200",
    topStripe: "bg-teal-500",
    sidebarHover: "hover:bg-teal-500/[0.10]",
    sidebarActive: "bg-teal-500/[0.18]",
    sidebarActiveDot: "bg-teal-400",
  },
  "Notes": {
    icon: StickyNote,
    bg: "bg-amber-50",
    text: "text-amber-600",
    accent: "amber",
    activeBg: "bg-amber-500/[0.08]",
    activeText: "text-amber-600",
    dot: "bg-amber-500",
    border: "border-amber-200",
    topStripe: "bg-amber-500",
    sidebarHover: "hover:bg-amber-500/[0.10]",
    sidebarActive: "bg-amber-500/[0.18]",
    sidebarActiveDot: "bg-amber-400",
  },
};

const DEFAULT_IDENTITY = {
  icon: null,
  bg: "bg-stone-50",
  text: "text-stone-500",
  accent: "stone",
  activeBg: "bg-[--k-primary]/[0.08]",
  activeText: "text-[--k-primary]",
  dot: "bg-[--k-primary]",
  border: "border-[--k-border]",
  topStripe: "bg-[--k-primary]",
  sidebarHover: "hover:bg-white/[0.06]",
  sidebarActive: "bg-white/10",
  sidebarActiveDot: "bg-white",
};

export function getAppIdentity(appName) {
  return APP_IDENTITY[appName] || DEFAULT_IDENTITY;
}

export { APP_IDENTITY };
